### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by unostella** [xErik/ng-if-bootstrap-grid#1]
Just wanted to say <code>thank you</code>, these directives are exactly what we needed for our project!

**Comment by xErik** [comment]
You are welcome! Let me know if something can be improved.

**Comment by unostella** [comment]
Currently using it in parallel with https://github.com/jacopotarantino/angular-match-media so that I can also use `if (screenSize.is('xs')) ...` in my controller. Then in views I use `<div ng-if-bootstrap-grid="xs">`
Anyway, I am good with that so thanks again.
