### ISSUE TITLE
Convert this to a bower package

### ISSUE THREAD

**Issue by navarroaxel** [xErik/ng-if-bootstrap-grid#2]

**Comment by xErik** [comment]
I do not use bower. Do I basically need to add a _bower.json_, or is there more to it?

**Comment by navarroaxel** [comment]
1) You can use use the the bower init to create it.
2) You need to do a release, you can do that with repo home page.
3) The module.exports is not used in a bower package.

**Comment by xErik** [comment]
If the module.exports is not used, do I need to change the code?
