### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by Younesi** [xErik/ng-if-bootstrap-grid#3]
Hi, package is not working! I have linked AJS and defined  ng-app directive and copied your codes, IT DOES NOT WORK, my own codes also don't work, please help I need to come up with a soloution to detect  bootstrap grid

**Comment by xErik** [comment]
Could you provide some code that let's me reproduce the problem?

**Comment by Younesi** [comment]
I'm using version 0.1.0
Here is my code:
   `<head>`<br>
`<script src="{{ URL::asset('public/assets/bower_components/angular/angular.min.js') }}">`
        `angular.module('myApp',[require('ng-if-bootstrap-grid').name]);`
  `</script>`<br>
`</head>`<br>
`<div class="container"  ng-app="myApp">`<br>
`<div class="hidden-xs col-sm-3 sidebar-offcanvas"  ng-if-not-bootstrap-grid="xs"> </div>`
`<div class="visible-xs  hidden-sm col-xs-12 sidebar-offcanvas"  ng-if-bootstrap-grid="xs">`<br>
`</div>`

**But both grids always get shown.**
Thank in advance for your help

**Comment by xErik** [comment]
What bootstrap version are you using?
What angularjs version are you using?

Does it work when adding the missing `row`-div?

```html
<div ng-app="myApp">
  <div class="row">
		<div class="hidden-xs col-sm-3" ng-if-not-bootstrap-grid="xs">A</div>
		<div class="visible-xs hidden-sm col-xs-12" ng-if-bootstrap-grid="xs">B</div>
  </div>
</div>
```

**Comment by Younesi** [comment]
Hi,In order to solve  the problem  I installed  [Browserify](https://github.com/substack/node-browserify) and [Webpack](https://webpack.github.io) which are  CommmonJS implementation. but still got the error of :
`Uncaught ReferenceError: require is not defined`
the step for installing browserify  is this command: `npm install -g browserify`

**Comment by xErik** [comment]
Did you run `browserify` on the command line to create a build?

`browserify` is not meant to run in the browser.

**Comment by Younesi** [comment]
There is no error in client-side now, but package is not working yet, I'm done with it.
Thanks for your helps.

**Comment by xErik** [comment]
Mind your words.
